In [209]:
import numpy as np
import matplotlib
import pandas as pd

In [210]:
dataset = pd.read_csv('/Users/wzhang/Downloads/lake_erie_habs_W4_6_8_9_12_13_16_2013-2020.xlsx - HAB_data (1).csv')

In [211]:
print(dataset)

          Date  Site  Latitude (decimal deg)  Longitude (decimal deg)  \
0    5/29/2013   WE6                 41.7134                 -83.3804   
1    5/29/2013   WE8                 41.8343                 -83.3633   
2    5/29/2013   WE4                 41.8267                 -83.1930   
3    6/10/2013   WE6                 41.7144                 -83.3805   
4    6/10/2013   WE8                 41.8353                 -83.3631   
..         ...   ...                     ...                      ...   
834  10/5/2020   WE9                 41.7176                 -83.4239   
835  10/5/2020  WE16                 41.6599                 -83.1468   
836  10/5/2020  WE13                 41.7436                 -83.1526   
837  10/5/2020  WE12                 41.7040                 -83.2552   
838  10/5/2020   WE4                 41.8267                 -83.1947   

     Secchi Depth (m)  CTD Temperature (°C)  \
0                 1.6                  18.5   
1                 1.0        

In [233]:
labels = dataset.iloc[:,16:].values
print(labels)

[[  2.15]
 [  3.65]
 [  4.34]
 [ 23.39]
 [  5.3 ]
 [  9.83]
 [ 47.69]
 [  3.42]
 [  4.18]
 [  3.27]
 [  1.64]
 [ 10.76]
 [  5.67]
 [  2.77]
 [  3.3 ]
 [  0.71]
 [  6.19]
 [ 13.45]
 [ 61.41]
 [ 34.21]
 [ 17.28]
 [ 38.68]
 [  9.54]
 [117.66]
 [  5.05]
 [  2.54]
 [ 15.15]
 [ 18.52]
 [  4.4 ]
 [181.35]
 [ 52.  ]
 [ 26.8 ]
 [104.76]
 [156.17]
 [ 34.02]
 [243.81]
 [114.53]
 [ 62.18]
 [118.17]
 [ 71.18]
 [ 17.85]
 [223.36]
 [137.14]
 [ 42.75]
 [121.54]
 [203.01]
 [ 65.33]
 [101.44]
 [ 89.39]
 [ 11.73]
 [105.95]
 [ 74.1 ]
 [  3.8 ]
 [ 60.36]
 [ 52.17]
 [ 39.44]
 [ 62.5 ]
 [ 21.94]
 [ 36.86]
 [ 50.62]
 [  4.31]
 [  3.52]
 [  3.86]
 [  5.67]
 [ 23.04]
 [  5.74]
 [  5.09]
 [ 34.37]
 [ 12.26]
 [ 29.81]
 [ 35.97]
 [ 10.62]
 [  7.88]
 [ 12.93]
 [ 46.27]
 [  3.15]
 [  3.3 ]
 [  6.98]
 [  3.55]
 [ 19.29]
 [  3.79]
 [  4.28]
 [  7.74]
 [  3.96]
 [ 68.1 ]
 [  8.8 ]
 [  7.81]
 [ 18.62]
 [  5.95]
 [126.14]
 [ 42.11]
 [  5.63]
 [ 33.15]
 [  6.12]
 [ 71.62]
 [ 46.53]
 [  6.74]
 [ 54.46]
 [ 18.11]
 [ 97.96]


In [234]:
vals = pd.DataFrame(dataset.iloc[:,4:15].values)
print(vals)

      0     1      2     3      4      5      6      7      8     9     10
0    1.6  18.5  391.3  7.60   8.44  48.51  33.01  62.95  2.420  0.42  0.06
1    1.0  20.3  379.8  7.60   9.98  37.85  18.68  40.25  2.110  0.45  0.07
2    1.5  19.8  296.2  7.60   4.36  15.58   4.70  13.07  0.900  0.32  0.06
3    0.5  20.7  341.2  7.60  21.50  58.18   8.66   7.34  1.340  1.22  0.18
4    0.7  23.5  301.3  7.50  15.70  48.33  15.90  23.02  1.060  0.69  0.10
..   ...   ...    ...   ...    ...    ...    ...    ...    ...   ...   ...
834  0.8  14.4  313.1  9.00   9.38  47.68  18.77  20.71  0.069  0.98  0.17
835  1.8  15.4  249.6  8.90   3.48  22.20   8.86  20.53  0.105  0.46  0.09
836  1.8  15.7  221.3  8.97   2.30  14.30   5.21  12.07  0.249  0.27  0.04
837  1.0  15.2  258.4  9.07   7.24  28.96   9.31   2.89  0.002  0.83  0.09
838  3.5  15.7  226.4  8.54   1.27  13.01   5.44  23.46  0.271  0.19  0.02

[839 rows x 11 columns]


In [224]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(vals,labels,test_size=0.2,random_state=0)
(X_train - np.min(X_train)) / (np.max(X_train) - np.min(X_train))
(X_test - np.min(X_test)) / (np.max(X_test) - np.min(X_test))

0         1         2         3         4         5         6   \
375  0.000359  0.002511  0.231058  0.006221  0.009400  0.035290  0.016310   
145  0.000287  0.010548  0.240099  0.006386  0.080368  1.000000  0.005726   
642  0.000538  0.013490  0.210320  0.005956  0.021312  0.092739  0.052741   
231  0.000287  0.018370  0.172074  0.006745  0.006630  0.030231  0.010677   
668  0.000897  0.018657  0.185420  0.004449  0.004456  0.015916  0.005001   
..        ...       ...       ...       ...       ...       ...       ...   
467  0.000144  0.013490  0.181115  0.006092  0.037457  0.047812  0.007018   
666  0.000538  0.018944  0.238234  0.004808  0.013849  0.039452  0.008805   
685  0.001435  0.017652  0.167122  0.005023  0.005375  0.012708  0.002540   
622  0.000538  0.006386  0.191879  0.007032  0.029923  0.014308  0.004650   
380  0.000574  0.008683  0.288822  0.006092  0.004937  0.028638  0.005123   

           7         8         9         10  
375  0.120042  0.000689  0.000416  0.000079  
145  0.000287  0.000100  0.022733  0.004241  
642  0.032714  0.001333  0.000631  0.000093  
231  0.000459  0.000001  0.002354  0.000373  
668  0.005827  0.000454  0.000409  0.000079  
..        ...       ...       ...       ...  
467  0.006695  0.000129  0.002956  0.000531  
666  0.008244  0.000469  0.001435  0.000244  
685  0.003294  0.000130  0.001392  0.000222  
622  0.044776  0.000320  0.000581  0.000057  
380  0.222827  0.000445  0.001758  0.000301  

[168 rows x 11 columns]

In [255]:
import tensorflow as tf

In [256]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from numpy import absolute
from numpy import mean
from numpy import std

In [257]:
model = Ridge(alpha=100)

In [258]:
model.fit(X_train,Y_train)

Ridge(alpha=100)

In [259]:
res = model.predict(X_test)
print(res)

[[-1.19882071e+01]
 [ 4.05171544e+02]
 [ 1.39268286e+01]
 [ 5.15438783e+01]
 [ 2.34234065e+01]
 [ 5.33475323e+01]
 [ 7.01500538e+01]
 [ 8.28563048e+01]
 [ 2.40605606e+01]
 [ 1.49472569e+01]
 [ 3.29655299e+01]
 [ 7.72945996e+01]
 [ 2.00530006e+01]
 [ 3.48342040e+01]
 [-1.61793895e+00]
 [ 1.67655012e+01]
 [ 9.34383919e+00]
 [ 1.22013372e+01]
 [ 1.06931550e+01]
 [ 5.43841613e+01]
 [ 2.96721548e+01]
 [-5.60540456e+00]
 [ 2.84012752e+01]
 [ 2.77150734e-01]
 [ 1.97284932e+01]
 [ 1.82191704e+01]
 [ 5.59659577e+01]
 [ 2.74761753e+01]
 [ 8.85582838e+01]
 [ 2.18571006e+01]
 [ 8.80880194e+00]
 [ 3.61850817e+01]
 [ 1.52749968e+01]
 [ 2.32283514e+01]
 [ 3.65418258e+01]
 [ 3.70709605e+01]
 [ 2.88764084e+01]
 [ 1.62848811e+01]
 [ 2.15583795e+01]
 [ 2.53236566e+01]
 [ 1.48734418e+01]
 [ 1.43055764e+01]
 [ 8.39936460e+00]
 [ 1.77308620e+01]
 [ 1.02895514e+01]
 [ 3.91390698e+01]
 [ 3.50689556e+01]
 [ 1.98683314e+01]
 [ 2.35577171e+01]
 [-2.67701702e-01]
 [ 3.26602367e+01]
 [ 1.87167436e+01]
 [ 6.4924745

In [260]:
print(Y_test)

[[  0.77]
 [466.5 ]
 [  1.73]
 [ 48.64]
 [  6.82]
 [ 88.48]
 [  4.25]
 [ 48.44]
 [ 11.6 ]
 [  7.92]
 [ 43.53]
 [150.15]
 [  2.48]
 [ 14.1 ]
 [  3.86]
 [ 16.17]
 [  4.18]
 [  3.76]
 [  8.03]
 [ 70.2 ]
 [ 41.66]
 [  2.18]
 [  8.24]
 [  3.43]
 [ 26.8 ]
 [  8.65]
 [ 36.61]
 [  9.98]
 [190.08]
 [  5.48]
 [ 12.9 ]
 [  6.27]
 [ 39.44]
 [ 17.29]
 [ 42.47]
 [ 14.92]
 [ 26.3 ]
 [  4.29]
 [ 14.61]
 [  8.81]
 [  8.29]
 [ 18.52]
 [ 12.25]
 [  3.04]
 [  3.75]
 [  7.93]
 [ 37.75]
 [ 11.42]
 [  3.3 ]
 [  2.68]
 [ 32.91]
 [ 15.27]
 [183.42]
 [ 66.79]
 [ 44.48]
 [ 22.69]
 [ 23.99]
 [  7.46]
 [ 20.45]
 [  5.11]
 [  1.65]
 [  2.06]
 [ 29.12]
 [ 22.62]
 [  1.46]
 [ 54.02]
 [  3.97]
 [  6.98]
 [ 52.11]
 [119.72]
 [ 14.61]
 [  1.93]
 [ 50.96]
 [ 16.  ]
 [ 53.09]
 [  1.74]
 [ 44.09]
 [  3.56]
 [ 35.53]
 [  1.14]
 [ 24.77]
 [  3.91]
 [ 21.67]
 [  9.97]
 [ 41.47]
 [  6.36]
 [  3.56]
 [  2.8 ]
 [ 47.71]
 [ 30.07]
 [ 60.26]
 [ 17.85]
 [  1.63]
 [  2.06]
 [ 25.53]
 [ 89.16]
 [  3.59]
 [ 17.4 ]
 [ 16.26]
 [  6.61]


In [261]:
from sklearn.metrics import r2_score 

In [262]:
r2 = r2_score(Y_test, res) 
print(r2)

0.5184804637870508


In [267]:
from sklearn.metrics import mean_absolute_error

In [268]:
mae = mean_absolute_error(Y_test,res)
print(mae)

1801.0741754613998


In [265]:
from sklearn.metrics import mean_absolute_percentage_error
mape = mean_absolute_percentage_error(Y_test,res)
print(mape)

1.7604572134959668


In [269]:
from sklearn.metrics import root_mean_squared_error
rmse = root_mean_squared_error(Y_test,res)
print(rmse)

42.43906426232086
